### ISSUE TITLE
Roadmap for Caddy 1 / Caddy 2

### ISSUE THREAD

**Issue by dhoppe** [voxpupuli/puppet-caddy#63]
I would like to get these issues solved:
- [ ] Change default values #54 
- [ ] Migrate from .erb to .epp templates #55
- [ ] Support a specific version #59

End support for Caddy 1
- [ ] Create a final release
- [ ] Announce end of life

Add support for Caddy 2
- [ ] Add support for .deb / .rpm releases #62
- [ ] Drop support for CentOS 6 / RHEL 6
- [ ] Support for caddy v2 #34
- [ ] Make Systemd more configurable #56

I think the issue #57 is obsolete, because Caddy 2 uses a different Systemd unit file. 

The issue #58 might be obsolete, because Caddy 2 provides an API to configure the web server.

**Comment by alexjfisher** [comment]
Why don't you create a github milestone?

**Comment by dhoppe** [comment]
Good question. So far I have not needed this feature. Besides I am working on all the pull requests right now. Time is ticking. ;)

**Comment by shibumi** [comment]
Just a few things:

1. Caddys configuration file format has changed completely. Things that work, will no longer work in caddy2
2. There are two systemd service files now
3. It's very likely, that there will be no official  debian package, due to their strict golangp packaging policy.

**Comment by dhoppe** [comment]
I know. That is why I would like to make a final release that ends the support of Caddy 1. After that, the download will only be possible via GitHub anyway, so no installations with additional plugins will be possible. 

I have also seen that Caddy 2 comes with its own API for configuration. 

According to the website there is a repository for Debian packages. I also didn't refer to the official repositories of the Debian project ;)

**Comment by dhoppe** [comment]
I will close this issue in favour of these two milestones:
* https://github.com/voxpupuli/puppet-caddy/milestone/1
* https://github.com/voxpupuli/puppet-caddy/milestone/2
